#!/bin/sh
set -e

dir=/var/www/slideshow-pro-director

usage() {
  echo "usage: $0 COMMAND"
  echo
  echo "Manage slideshow-pro-director source tarball lifecycle."
  echo
  echo "Commands:"
  echo "   extract  extract slideshow-pro-director source tarball into directory $dir if not already done."
  echo "   delete   delete extracted slideshow-pro-director source located into $dir if not already done."
  echo
}

case "$1" in
  extract)
    mkdir -p "$dir"
    if [ ! -f "$dir/.docker-extracted" ]; then
      tar -Jxf /tmp/slideshow-pro-director.tar.xz -C "$dir" --strip-components=1
      touch "$dir/.docker-extracted"
    fi
    ;;

  delete)
    rm -rf "$dir"
    ;;

  *)
    usage
    exit 1
    ;;
esac
